[package]
name = "hydra-cli"
version.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later"
repository.workspace = true
homepage.workspace = true
description = "Multi-source download accelerator and file retriever CLI"

[[bin]]
name = "hydra"
path = "src/main.rs"

[dependencies]
hydra-core = { workspace = true }
hydra-net = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
crossterm = { workspace = true }
sha2 = { workspace = true }
md-5 = { workspace = true }
sha1 = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap_complete = { workspace = true }

[lints]
workspace = true
